const newSection2 = document.createElement("section");
newSection2.id = "b";
newSection2.textContent = "Section2";
newSection2.classList.add("box");
newSection2.classList.add("bg1");
newSection2.classList.add("box", "bg1");
document.body.append(newSection2);
newSection2.style.color = "white";
newSection2.textContent += "😁";
document.body.prepend(newSection2);
const newSection3 = document.createElement("section");
newSection3.id = "c";
newSection3.classList.add("box", "bg1");
newSection3.style.width = "15rem";
newSection3.textContent = "Section3 🥰";
newSection3.classList.remove("bg1");
document.body.append(newSection3);
// document.body.insertBefore(newSection3,newSection2);
const newSection4 = document.createElement("section");
newSection4.id = "c" //parameters
newSection4.classList.add("box", "bg1");
document.body.append(newSection4);
newSection4.classList.remove("bg1");
newSection4.textContent = "Section4";
newSection4.style.backgroundColor = "seagreen";
newSection4.style.width = "20rem";
newSection4.style.height
newSection2.remove();
// document.getElementById("b").remove();
// newSection2.style.cssText="color:red; font-size:20px;
// document.body.firstElementChild.style.color="red";
// document.body.lastElementChild.style.color="red";
const section = document.getElementById("a");
var firstElement = document.body.firstElementChild;
firstElement.style.fontSize = "1.25rem";
console.log(firstElement);
let lastElement = document.body.lastElementChild;
lastElement.style.fontSize = "2.5rem";